name: SAST Scans

on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  RunTerraformValidation:
    name: Run Terraform Validation
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/.github/workflows/standard-pipeline.yml@main
    with:
      working-directory: "."
      use-backend: false
      terraform-version: "1.15.0"

  checkov-scan:
    uses: Home-Office-Digital/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.18.0
    with:
      path: '.'
  sonarqube-scanner:
    uses: Home-Office-Digital/core-cloud-workflow-sonarqube-scan/.github/workflows/sonarqube-scan.yaml@1.1.8
    secrets:
      sonar-token: ${{ secrets.sonar_token }}
      sonar-host-url: ${{ secrets.sonar_host_url }}