name: SAST Scans

on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  RunTerraformValidation:
    name: Run Terraform Validation
    runs-on: ubuntu-latest
    env:
      TF_INPUT: "false"

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.9.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/test@main
        continue-on-error: true
        with:
          working-directory: .

      - name: Terraform Test Fallback
        if: success() || failure()
        run: terraform test -no-color

      - name: TFLint
        uses: Home-Office-Digital/core-cloud-workflow-tflint-scan@main

  checkov-scan:
    uses: Home-Office-Digital/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.18.0
    with:
      path: '.'
  sonarqube-scanner:
    uses: Home-Office-Digital/core-cloud-workflow-sonarqube-scan/.github/workflows/sonarqube-scan.yaml@1.1.8
    secrets:
      sonar_token: ${{ secrets.sonar_token }}
      sonar_host_url: ${{ secrets.sonar_host_url }}